topologies:
  simple_topology: true


design_exploration:
  single_bend: True
  double_bend : True

plot:
  Rectangle: True
  Corner Points: False
  Planes: False
  Bends: True
  Bending Points: True
  Flange: True
  Flange Points: True
  Elements: True

  point_size: 30
  font_size: 30
  
  BP1_color: "red"
  BP2_color: "blue"
  
  FPA1_color: "green"
  FPA2_color: "green"
  FPB1_color: "orange"
  FPB2_color: "orange"

  debug_labels: True   # toggle labels for bends, BPs, tabs, planes

3D: True
2D: False