topologies:
  simple_topology: true

design_exploration:
  single_bend: False
  double_bend : True

design_rules:
  Min Bend Angle: 40
  Min Flange Length: 10
  Min Flange Width: 30

filter:
  Min Flange Width: True
  Min Bend Angle: True
  Tabs cover Rects: False
  Lines Cross: True
  Collisions: True
  Too thin segments: False

plot:
  Rectangles: True
  Tab Points: False
  Tabs: True
  Flanges: True
  Triangulate Tabs: True
  Corner Points: False
  
  Labels: True   # Turn off to increase plotting speed
  Legend: True
  Grid: True
  Export Buttons: True

  point_size: 30
  font_size: 40