topologies:
  Simple Topology: False
  Specific Topology: True #Edit sequence in src/hgen_sm/determine_sequences/choose_pairs.py

design_exploration:
  single_bend: True
  double_bend : True

design_rules:
  Min Bend Angle: 35
  Min Flange Length: 10
  Min Flange Width: 30

filter:
  Min Flange Width: True
  Min Bend Angle: True
  Tabs cover Rects: True
  Lines Cross: True
  Collisions: True 
  Too thin segments: False

plot:
  Rectangles: True
  Tab Points: False
  Tabs: True
  Flanges: True
  Triangulate Tabs: True
  Corner Points: False
  
  Labels: False   # Turn off to increase plotting speed
  Legend: True
  Grid: True
  Export Buttons: True

  point_size: 30
  font_size: 40